name = "sonicjs-ai"
main = "src/index.ts"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = ""

[build.upload]
format = "modules"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

# Static assets
[assets]
directory = "./public"
binding = "ASSETS"

[vars]
ENVIRONMENT = "development"
# Cloudflare Images configuration (optional)
# IMAGES_ACCOUNT_ID = "your-account-id"
# CDN_DOMAIN = "media.yourdomain.com"

[[d1_databases]]
binding = "DB"
database_name = "sonicjs-dev"
database_id = "874cad37-313c-4d71-97fa-ad7184526f5a"

# R2 Bucket for media storage
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sonicjs-media-dev"

# KV Namespace for caching
[[kv_namespaces]]
binding = "CACHE_KV"
id = "placeholder-dev"
preview_id = "placeholder-preview-dev"

[env.preview]
name = "sonicjs-ai-preview"

[env.preview.vars]
ENVIRONMENT = "preview"
# IMAGES_ACCOUNT_ID = "your-account-id"
# CDN_DOMAIN = "media-preview.yourdomain.com"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "sonicjs-dev"
database_id = "874cad37-313c-4d71-97fa-ad7184526f5a"

[[env.preview.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sonicjs-media-preview"

[[env.preview.kv_namespaces]]
binding = "CACHE_KV"
id = "placeholder-preview"
preview_id = "placeholder-preview-preview"

[env.production]
name = "sonicjs-ai-prod"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "sonicjs-ai"
database_id = "583c089c-1a4a-477d-9d58-06c07bf7c1d7"

[[env.production.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sonicjs-media-prod"

[[env.production.kv_namespaces]]
binding = "CACHE_KV"
id = "placeholder-prod"
preview_id = "placeholder-preview-prod"
