# ============================================================================
# BASE CONFIGURATION
# ============================================================================
name = "sonicjs-ai"
main = "src/index.ts"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

# ============================================================================
# DEVELOPMENT SETTINGS
# ============================================================================
[dev]
port = 8787
persist_to = ".wrangler/state/v3"
# Reduce logging verbosity to avoid noise from high-frequency endpoints
# Set WRANGLER_LOG environment variable to control log level
# Options: "none", "error", "warn", "info", "log", "debug"

[build]
command = ""

# ============================================================================
# STATIC ASSETS
# ============================================================================
[assets]
directory = "./public"
binding = "ASSETS"

# ============================================================================
# DEVELOPMENT ENVIRONMENT (default)
# ============================================================================
[vars]
ENVIRONMENT = "development"
# Set to "true" to run E2E tests before every git push
RUN_E2E_ON_PUSH = "false"
# Enable experimental features (plugins menu, etc.)
ENABLE_EXPERIMENTAL_FEATURES = "true"
# Cloudflare Images configuration (optional)
# IMAGES_ACCOUNT_ID = "your-account-id"
# CDN_DOMAIN = "media.yourdomain.com"

# --- D1 Database (Development) ---
[[d1_databases]]
binding = "DB"
database_name = "sonicjs-dev"
database_id = "874cad37-313c-4d71-97fa-ad7184526f5a"

# --- R2 Storage (Development) ---
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sonicjs-media-dev"

# --- KV Cache (Development) ---
[[kv_namespaces]]
binding = "CACHE_KV"
id = "a16f8246fc294d809c90b0fb2df6d363"
preview_id = "25360861fb2745fab3b1ef2f0f13ffc8"

# ============================================================================
# PREVIEW ENVIRONMENT
# ============================================================================
[env.preview]
name = "sonicjs-ai-preview"

[env.preview.vars]
ENVIRONMENT = "preview"
ENABLE_EXPERIMENTAL_FEATURES = "false"
# IMAGES_ACCOUNT_ID = "your-account-id"
# CDN_DOMAIN = "media-preview.yourdomain.com"

# --- D1 Database (Preview) ---
[[env.preview.d1_databases]]
binding = "DB"
database_name = "sonicjs-dev"
database_id = "874cad37-313c-4d71-97fa-ad7184526f5a"

# --- R2 Storage (Preview) ---
[[env.preview.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sonicjs-media-preview"

# --- KV Cache (Preview) ---
[[env.preview.kv_namespaces]]
binding = "CACHE_KV"
id = "6fc451bee9bb412ebd1d325723779c9c"
preview_id = "38c54bd2b55643c097412fa3464c2ddd"

# ============================================================================
# PRODUCTION ENVIRONMENT
# ============================================================================
[env.production]
name = "sonicjs-ai-prod"

[env.production.vars]
ENVIRONMENT = "production"
ENABLE_EXPERIMENTAL_FEATURES = "false"

# --- D1 Database (Production) ---
[[env.production.d1_databases]]
binding = "DB"
database_name = "sonicjs-ai"
database_id = "583c089c-1a4a-477d-9d58-06c07bf7c1d7"

# --- R2 Storage (Production) ---
[[env.production.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sonicjs-media-prod"

# --- KV Cache (Production) ---
[[env.production.kv_namespaces]]
binding = "CACHE_KV"
id = "7171ca98640e43b6b33dbff516a5a6cf"
preview_id = "aed99543752d438b8051a0b6809ced10"
